### ISSUE TITLE
Inclusion of "udeft" for detection of 1D experiment & addition of HMQC experiment detection

### ISSUE THREAD

**Issue by michaelwenk** [cheminfo/nmr-parser#10]
https://github.com/cheminfo/nmr-parser/blob/2e17dac3e31daed8ec74accc03b42b3797b7e7f8/src/utils/getSpectrumType.js#L27

@jobo @lpatiny 
1) We need to add "udeft" for 1d too, I guess. That occurred in some test cases of 1D Bruker files. 

2) It would also be good to have the detection of HMQC experiment. Something like:

`if (pulse.includes('hmqc')) {
    return 'hmqc';
  }`

**Comment by jobo322** [comment]
Hello @michaelwenk do you have a zip file or jcamp with those kind of experiments

**Comment by michaelwenk** [comment]
@jobo322 Thanks for the additions! But the "udeft" should be added to following line to return "1d".

https://github.com/cheminfo/nmr-parser/blob/497379052a117c7ac62f437e068560c854d8d6f1/src/utils/getSpectrumType.js#L28

**Comment by lpatiny** [comment]
@michaelwenk What is udeft ? A pulse sequence for 1d spectrum ?
Not important to have this information that it is udeft ?

@jobo322 There is an extra space on line https://github.com/cheminfo/nmr-parser/blob/497379052a117c7ac62f437e068560c854d8d6f1/src/utils/getSpectrumType.js#L55

**Comment by michaelwenk** [comment]
@lpatiny Yes, this "udeft" occurs in some 13C spectra (Bruker) in the pulse sequence property. 
To keep the information that it is "udeft", I actually don't know whether that is necessary.
@jobo322 already received one of such spectra from me to test. It should be around two or three years old.

**Comment by jobo322** [comment]
Yes it was my. I got the idea wrongly. At the moment if the experiment is not possible to determine returns 1d or 2d depending of the dimension.
