### ISSUE TITLE
numberOfPoints from TD or actual data ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-parser#54]
Currently we are looking for the numberOfPoints in the TD property.

https://github.com/cheminfo/nmr-parser/blob/d49e48b5a5abf7af4edac77f6fcf0a040309b20e/src/utils/getInfoFromJCAMP.js#L81-L82

however in the FID we are using in the testcases TD is 256k

https://github.com/cheminfo/nmrium/blob/6c5d9f3248f60993cebb0d5cb47a44213f39f864/public/data/cytisine/13C_Cytisin_600_fid.dx#L1477-L1478

But the actual number of points in the data is 128k:

https://github.com/cheminfo/nmrium/blob/6c5d9f3248f60993cebb0d5cb47a44213f39f864/public/data/cytisine/13C_Cytisin_600_fid.dx#L1665-L1666

So I would expect to have as numberOfPoints 128k and not 256k.

@jwist What do you think ? Guido was asking this question.

**Comment by jobo322** [comment]
It was done and handled by nmr-load-save package now
